name: objectbox_flutter_libs
version: 1.2.0
repository: https://github.com/objectbox/objectbox-dart
homepage: https://objectbox.io
description: ObjectBox is a super-fast NoSQL ACID compliant object database. This package contains flutter runtime libraries for ObjectBox.

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  # This is here just to ensure compatibility between objectbox-dart code and the libraries used
  # You should still depend on objectbox directly in your Flutter application.
  objectbox: ^1.3.0
  path_provider: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.objectbox.objectbox_flutter_libs
        pluginClass: ObjectboxFlutterLibsPlugin
      ios:
        pluginClass: ObjectboxFlutterLibsPlugin
      linux:
        pluginClass: ObjectboxFlutterLibsPlugin
      macos:
        pluginClass: ObjectboxFlutterLibsPlugin
      windows:
        pluginClass: ObjectboxFlutterLibsPlugin