name: Build and test

# Avoid duplicate builds for pull requests, allow manual trigger.
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  generator:
    runs-on: ubuntu-20.04
    container:
      image: google/dart:latest
    steps:
      - uses: actions/checkout@v2
      - name: Install ObjectBox C-API
        run: ./install.sh
      - name: Test
        run: ./generator/test.sh

  # make sure the init script doesn't stop working - it's not something we usually run during normal development
  init-script:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
      - run: ./tool/init.sh

  lib:
    strategy:
      fail-fast: false # To see all Dart SDKs that fail, also sometimes with more helpful errors.
      matrix:
        os:
          - windows-2019
          - macos-10.15
          - ubuntu-20.04
        sdk:
          - stable
          - 2.15.1
          - 2.14.4
          - 2.13.4
          - 2.12.0  # currently the lowest fully supported version (i.e. generator + lib)
    runs-on: ${{ matrix.os }}
    steps:
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - run: dart --version
      - uses: actions/checkout@v2
      - name: Install ObjectBox C-API
        working-directory: objectbox
        run: ../install.sh
      - name: Test
        working-directory: objectbox
        run: |
          ../tool/pub.sh get
          ../tool/pub.sh run build_runner build
          ../tool/pub.sh run test

  valgrind:
    runs-on: ubuntu-20.04
    steps:
      - uses: dart-lang/setup-dart@v1
      - uses: actions/checkout@v2
      - name: Install ObjectBox C-API
        run: ./install.sh
      - name: Install Valgrind
        run: ./tool/apt-install.sh valgrind
      - name: Test
        working-directory: objectbox
        # let tests know we want a faster/shorter version, if available (to prevent timeouts in CI)
        env:
          TEST_SHORT: 1
        run: |
          ../tool/pub.sh get
          ../tool/pub.sh run build_runner build
          ./tool/valgrind.sh

  flutter-integration-test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2019
          - macos-10.15
          - ubuntu-20.04
        channel:
          - beta
          - stable
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.channel }}
      - uses: actions/setup-java@v2 # macos-10.15 and windows-2019 default to Java 8, but Android Plugin requires 11
        with:
          distribution: 'temurin'
          java-version: '11'
      - run: echo $PATH
      - run: flutter --version
      - if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: ./tool/apt-install.sh ninja-build pkg-config libgtk-3-dev
      - run: make integration-test
        working-directory: objectbox